server:
  port: 8081

spring:
  application:
    name: ms-pedidos
  datasource:
    url: jdbc:postgresql://localhost:5431/pedidos_db
    username: user_pedidos
    password: password_pedidos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j:
  circuitbreaker:
    instances:
      inventarioCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

logging:
  level:
    org.hibernate.SQL: DEBUG

services:
  inventario:
    url: http://localhost:8082/inventario
